model_id: "math-specialized"
description: "Model fine-tuned on math problems with step-by-step solutions"
base_model_path: "models/base/llama-3.2-3b-base"
output_dir: "models/variants/math-specialized"
dataset_path: "data/processed/math_instruction.json"
format_type: "instruction"
batch_size: 1
gradient_accumulation: 8
learning_rate: 2e-5
epochs: 3
max_length: 512 